spring:
  application:
    name: DownTown tour
  datasource:
    url: jdbc:mysql://localhost:3306/downtown_tour
    username: downtown_tour_app
    password: downtown_tour_pas
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080