spring:
  application:
    name: DownTown tour
  datasource:
    url: jdbc:mysql://${DOWNTOWNTOUR_DB_ADDRESS}:${DOWNTOWNTOUR_DB_PORT}/${DOWNTOWNTOUR_DB_SCHEMA}
    username: ${DOWNTOWNTOUR_DB_USERNAME}
    password: ${DOWNTOWNTOUR_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080